objects:
  role:
    run:
      description: Role description.
      name: run
      version_added: null
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  filter: {}
  httpapi: {}
  inventory: {}
  lookup: {}
  module:
    temperature:
      description: Convert temperature to Fahrenheit or Celsius.
      name: temperature
      namespace: ""
      version_added: 1.0.0
  netconf: {}
  shell: {}
  strategy: {}
  test: {}
  vars: {}
version: 0.0.1
